image:
  - Ubuntu

stack:
  - node 8
  - node 10

version: "{build}"

clone_depth: 5

environment:
  matrix:
    - platform: "x64"

install:
  - npm ci

build: off

test_script:
  - node -v
  - npm -v
  - npm test

matrix:
  fast_finish: true

cache:
  - '$HOME/.npm -> .appveyor.yml,package.json,package-lock.json'
